import { Shield } from 'lucide-react';
import PublicNavbar from '../components/PublicNavbar';
import PublicFooter from '../components/PublicFooter';


const CLAUSES = [
  {
    id: 'intended-use',
    title: '1. Intended Use',
    content: `EbolaPreempt is a decision-support tool designed exclusively for authorised public health officers and administrators operating in a professional capacity within Rwanda's public health surveillance system.

The risk scores and alerts generated by this system are probabilistic indicators produced by an unsupervised machine learning model. They are intended to supplement not replace rofessional epidemiological judgement, manual surveillance activities, and established outbreak response protocols.

Risk scores must not be published, broadcast, or shared as public-facing community risk ratings. Doing so may cause unnecessary public alarm, social stigma toward residents of flagged districts, or unwarranted economic disruption to cross-border communities. Any use of EbolaPreempt outputs beyond internal public health decision-support is outside the scope of this licence.`,
  },
  {
    id: 'data-collected',
    title: '2. Data We Collect',
    content: `EbolaPreempt collects and processes the following categories of data:

User account data: Usernames and hashed passwords are stored in the PostgreSQL database for authentication purposes. JWT access tokens are issued on login and held in the browser session for the duration of the session.

Usage data: Alert acknowledgement actions are logged against the authenticated officer's account, recording which officer acknowledged which alert and when. This data is used solely for audit trail purposes within the public health system.

Operational data: All Prediction and Alert records are stored in the database, including district name, risk score, alert level, prediction timestamp, and data source reference.

EbolaPreempt does not collect, process, or store any personally identifiable health information about individuals. No patient records, clinical data, or identifiable community health records are handled by this system at any stage.`,
  },
  {
    id: 'secondary-data',
    title: '3. Third-Party and Secondary Data',
    content: `EbolaPreempt relies on four open epidemiological data sources:

(a) DRC Ebola confirmed case counts from the Humanitarian Data Exchange (HDX), published by INRB-UMIE under an open licence.
(b) BVD population mobility detection rates from HDX, published by WHO/AFRO.
(c) DRC health zone boundaries from HDX, published by WHO/OMS.
(d) Rwanda health facility locations from HDX, sourced from OpenStreetMap via Healthsites.io.

All four datasets are publicly available and carry open data licences. EbolaPreempt does not alter, sell, or redistribute this data. The accuracy of risk scores depends on the timeliness and completeness of DRC health zone reporting, which may be affected by conflict conditions in outbreak areas. Data reporting delays in DRC will propagate into Rwanda's district risk scores.

Each ingested record carries a data_source field and a source_reported_date field, making the provenance and recency of every data point traceable within the system.`,
  },
  {
    id: 'risk-disclaimer',
    title: '4. Risk Score Disclaimer',
    content: `The risk scores generated by EbolaPreempt are outputs of an Isolation Forest unsupervised anomaly detection model trained on seven weeks of epidemiological data (2026-W20 to 2026-W26). They carry the following known limitations:

No labelled ground truth: Rwanda has no historical domestic Ebola outbreak data. Standard precision, recall, and F1 metrics cannot be computed. Precision@5 (66%) and Spearman rank correlation (0.09) serve as proxy validation metrics from a Leave-One-Week-Out backtest.

Fixed anomaly rate: The model's contamination parameter is set to 0.1, meaning it always classifies exactly 10% of district-week records as anomalous regardless of the actual outbreak situation.

Limited training data: Seven weeks of training data is insufficient to capture seasonal or long-term epidemiological patterns.

A HIGH risk label does not constitute a confirmed or probable Ebola case in the district. A LOW risk label does not confirm the absence of cross-border transmission risk. All scores require professional interpretation before any operational response is initiated.`,
  },
  {
    id: 'user-responsibilities',
    title: '5. User Responsibilities',
    content: `By accessing EbolaPreempt, authorised users agree to the following responsibilities:

Credentials: Users are responsible for keeping their login credentials confidential. Sharing account credentials with unauthorised individuals is prohibited.

Professional use: Outputs must be interpreted in the context of broader epidemiological surveillance activities and professional public health judgement. Users must not rely solely on EbolaPreempt outputs when making decisions that affect community safety or resource allocation.

Acknowledgement actions: Alert acknowledgements are logged. Users are responsible for ensuring that acknowledgements reflect genuine review of the risk signal rather than routine dismissal.

Responsible disclosure: Any suspected system errors, data anomalies, or security vulnerabilities must be reported to the system administrator rather than publicised.`,
  },
  {
    id: 'data-retention',
    title: '6. Data Retention and Export',
    content: `All Prediction, Alert, and WeeklyDataRecord data is stored in the Neon PostgreSQL database hosted on Render's cloud infrastructure. Data is retained for the operational lifetime of the system.

Users may export prediction history at any time using the CSV export function on the Predictions page. Exported files contain district name, risk score, alert level, and prediction timestamp only . No personal user data is included in exports.

User account data (username, hashed password) is retained for as long as the account is active. Requests for account deletion should be directed to the system administrator at the contact address below.`,
  },
  {
    id: 'changes',
    title: '7. Changes to This Policy',
    content: `This Privacy Policy and EULA may be updated as the system evolves. Significant changes including changes to data collection scope, intended use boundaries, or third-party data sources will be communicated to registered users via the system dashboard before taking effect.

Continued use of EbolaPreempt after a policy update constitutes acceptance of the revised terms. The effective date of the current version of this document is 22 June 2026.`,
  },
  {
    id: 'contact',
    title: '8. Contact',
    content: `For questions about this Privacy Policy or EULA, data access requests, account deletion, or to report a security concern:

Email: b.niyonseng@alustudent.com
REC Ethics Clearance: Approval Code M26-BSE-071 · 22 June 2026
REC Contact: researchethics@alueducation.com`,
  },
];

function Privacy() {
  return (
    <div className="min-h-screen bg-[#F8FAFC] dark:bg-slate-950">
      <PublicNavbar />

      {/* Header */}
      <section className="bg-[#1E3A5F] py-16">
        <div className="max-w-7xl mx-auto px-6 flex items-start gap-5">
          <div className="w-12 h-12 rounded-xl bg-[#06B6D4]/20 flex items-center justify-center shrink-0 mt-1">
            <Shield size={24} className="text-[#06B6D4]" />
          </div>
          <div>
            <p className="text-[#06B6D4] text-xs font-semibold uppercase tracking-widest mb-3">Legal</p>
            <h1 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Privacy Policy &amp; End-User Licence Agreement
            </h1>
            <p className="text-white/60 text-base max-w-2xl leading-relaxed">
              This document governs the use of EbolaPreempt, the conditions under which data
              is collected and processed, and the responsibilities of all authorised users.
            </p>
            <p className="text-white/40 text-sm mt-3">
              Effective date: 22 June 2026 · REC Clearance Code: M26-BSE-071
            </p>
          </div>
        </div>
      </section>

      {/* Clauses */}
      <section className="max-w-4xl mx-auto px-6 py-16 space-y-8">
        {CLAUSES.map(({ id, title, content }) => (
          <div
            key={id}
            id={id}
            className="bg-white dark:bg-slate-800 rounded-xl border border-gray-100 dark:border-gray-700/50 shadow-sm p-6 scroll-mt-24"
          >
            <h2 className="text-base font-bold text-gray-800 dark:text-gray-100 mb-4 flex items-center gap-2">
              <span className="w-1 h-5 bg-[#06B6D4] rounded-full inline-block" />
              {title}
            </h2>
            <div className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed whitespace-pre-line">
              {content}
            </div>
          </div>
        ))}
      </section>

      {/* Quick navigation */}
      <section className="max-w-4xl mx-auto px-6 pb-16">
        <div className="bg-[#1E3A5F]/5 border border-[#1E3A5F]/10 rounded-xl p-6">
          <h3 className="font-semibold text-gray-800 dark:text-gray-200 mb-4 text-sm">Jump to Section</h3>
          <div className="flex flex-wrap gap-2">
            {CLAUSES.map(({ id, title }) => (
              <a
                key={id}
                href={`#${id}`}
                className="px-3 py-1.5 bg-white dark:bg-slate-800 border border-gray-200 dark:border-gray-600 rounded-lg text-xs text-gray-600 dark:text-gray-300 hover:border-[#06B6D4] hover:text-[#06B6D4] transition-colors"
              >
                {title}
              </a>
            ))}
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}

export default Privacy;
