# Generated by Django 5.2.15 on 2026-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='Rubavu', max_length=100)),
                ('week_start_date', models.DateField()),
                ('ebola_cases', models.IntegerField(default=0)),
                ('cases_lag_1wk', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('rainfall', models.FloatField(default=0.0)),
                ('ndvi_value', models.FloatField(default=0.0)),
                ('transit_volume', models.IntegerField(default=0)),
                ('transit_lag_1wk', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start_date'],
            },
        ),
    ]
