# Generated by Django 5.2.15 on 2026-06-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydatarecord',
            name='active_regional_cases',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydatarecord',
            name='border_inflow_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydatarecord',
            name='distance_to_outbreak_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydatarecord',
            name='isolation_capacity_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydatarecord',
            name='transit_hub_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydatarecord',
            name='week',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
