# Generated by Django 5.2.15 on 2026-06-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_weeklydatarecord_active_regional_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='cases_lag_1wk',
        ),
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='ebola_cases',
        ),
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='ndvi_value',
        ),
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='rainfall',
        ),
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='transit_lag_1wk',
        ),
        migrations.RemoveField(
            model_name='weeklydatarecord',
            name='transit_volume',
        ),
    ]
